name: Dependencies

on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: boolean

jobs:
  step-one:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        if: ${{ github.event.inputs.test == 'true' }}
        run: echo "Step 1"

  step-two:
    runs-on: ubuntu-latest
    needs: step-one

    steps:
      - name: Step 2
        if: ${{ github.event.inputs.test == 'true' }}
        run: echo "Step 2"

  step-three:
    runs-on: ubuntu-latest
    needs: step-two
    if: always()

    steps:
      - name: Step 3
        run: echo "Step 3"
