name: Dependencies

on:
  workflow_dispatch:
    inputs:
      plan:
        required: true
        type: boolean
      plan-failed:
        required: true
        type: boolean
      approval:
        required: true
        type: boolean

jobs:
  plan:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.plan == 'true' }}
    name: Plan

    steps:
      - name: Plan Success
        if: ${{ github.event.inputs.plan-failed == 'false' }}
        run: echo "Plan Success"

      - name: Plan Failed
        if: ${{ github.event.inputs.plan-failed == 'true' }}
        run: exit 1

  approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'true' && always() }}
    needs: plan
    environment: job-approval
    name: Approval

    steps:
      - name: Approval
        run: echo "Approval"

  execute:
    runs-on: ubuntu-latest
    needs: [plan, approval] 
    name: Execute
    if: ${{ always() && success() || !failure() || !cancelled() }}

    steps:
      - name: Execute
        run: echo "Execute"
