name: Dependencies

on:
  workflow_dispatch:
    inputs:
      plan:
        required: true
        type: boolean
      approval:
        required: true
        type: boolean

jobs:
  plan:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.plan == 'true' }}
    name: Plan

    steps:
      - name: Plan
        run: echo "Plan"

  approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'true' }}
    needs: plan
    environment: job-approval
    name: Approval

    steps:
      - name: Approval
        run: echo "Approval"

  execute:
    runs-on: ubuntu-latest
    needs: [plan, approval]
    name: Execute

    steps:
      - name: Execute
        run: echo "Execute"
