name: Dependencies

on:
  workflow_dispatch:
    inputs:
      one:
        required: true
        type: boolean
      two:
        required: true
        type: boolean

jobs:
  step-one:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.one == 'true' }}

    steps:
      - name: Step 1
        run: echo "Step 1"

  step-two:
    runs-on: ubuntu-latest
    needs: step-one
    environment: job-approval
